# Generated by Django 3.1.4 on 2020-12-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20201228_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
