# Generated by Django 3.1.4 on 2020-12-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_auto_20201229_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='expires_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
