# Generated by Django 3.1.4 on 2021-01-21 10:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetterRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=api.models.generate_unique_code, max_length=6, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guests_can_pause', models.BooleanField(default=False)),
                ('guests_skip_state', models.CharField(default='Voting: 2', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_song_id', models.CharField(max_length=50)),
            ],
        ),
    ]
