# Generated by Django 3.1.4 on 2021-01-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_betterroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betterroom',
            old_name='room_code',
            new_name='code',
        ),
    ]
