# Generated by Django 3.1.4 on 2021-01-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210121_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betterroom',
            name='guests_skip_state',
            field=models.CharField(default='Voting: 2', max_length=50),
        ),
    ]
